site_name: kato's note

theme:
    name: material
    language: 'ja'
    features:
        - header.autohide

markdown_extensions:
    - admonition
    - attr_list
    - fontawesome_markdown
    - pymdownx.tilde

extra_css:
    - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

extra:
    search:
        language: 'en, ja'
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/uvrub

copyright: Copyright &copy; 2020 Kato
