# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: install_dependence
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3 get-pip.py
          rm get-pip.py
          make install_dependence

      - name: build
        run: |
          make

      - name: push
        run: |
          git config user.name "${{ secrets.ACTION_USER_NAME }}"
          git config user.email "${{ secrets.ACTION_EMAIL }}"
          git add .
          git commit --allow-empty -m "Update [github actions]"
          git push "https://kato-k:${{ secrets.TOKEN }}@github.com/kato-k/note-book" HEAD
